name: macos

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-11
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        std: [11, 20]
        include:
          - shared: -DBUILD_SHARED_LIBS=ON

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{matrix.shared}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DENABLE_DEVELOPER_MODE=ON \
                $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          threads=`sysctl -n hw.logicalcpu`
          cmake --build . --config ${{matrix.build_type}} --parallel $threads

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest -C ${{matrix.build_type}}
        env:
          CTEST_OUTPUT_ON_FAILURE: True