name: windows

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments.
        platform: [x64]
        toolset: [v143]
        standard: [11, 20]
        shared: ["", -DBUILD_SHARED_LIBS=ON]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      # Use a bash shell for $GITHUB_WORKSPACE.
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -A ${{matrix.platform}} -T ${{matrix.toolset}} \
              -DCMAKE_CXX_STANDARD=${{matrix.standard}} \
              ${{matrix.shared}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DENABLE_DEVELOPER_MODE=ON \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        $threads = (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
        cmake --build . --config ${{matrix.build_type}} --parallel $threads

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -C ${{matrix.build_type}} -V
      env:
        CTEST_OUTPUT_ON_FAILURE: True

#    - name: Find Package Installation Test
#      working-directory: ${{runner.workspace}}
#      run: |
#        cmake --install .\build --config ${{matrix.build_type}} --prefix ${{runner.workspace}}\install
#
#        cmake ^
#        -S ${{runner.workspace}}\test\test_install\template_find_package_install_test ^
#        -B ${{runner.workspace}}\find_package_install_test_build ^
#        -A ${{matrix.platform}} -T ${{matrix.toolset}} ^
#        -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{matrix.shared}} ^
#        -DCMAKE_CXX_STANDARD=${{ matrix.std }} ^
#        -DCMAKE_PREFIX_PATH=${{runner.workspace}}\install
#
#        cmake ^
#        --build ${{runner.workspace}}\find_package_install_test_build ^
#        --config ${{matrix.build_type}} ^
#        --parallel $threads
#
#        cmake ^
#        --install ${{runner.workspace}}\find_package_install_test_build ^
#        --config ${{matrix.build_type}} ^
#        --prefix ${{runner.workspace}}\find_package_install_test_install
